init
e-faizov/gophermart pull request #1
Opened 2022-12-03 20:22 UTC by e-faizov

2022-12-13 11:06 UTC, rktkov requested changes

2022-12-13 11:06 UTC, rktkov commented on internal/updater/updater.go
> +	go s.worker()
Не предусмотрен механизм контролируемого завершения го-рутины. Например, во время завершения работы приложения. Стоит о нем подумать.

2022-12-19 15:08 UTC, e-faizov commented on internal/updater/updater.go
> +	go s.worker()
добавил завершение горутины при завершении приложения

2022-12-21 10:51 UTC, rktkov requested changes

2022-12-21 10:51 UTC, rktkov commented on internal/handlers/balance.go
> +	userID, err := getUserFromReq(r)
Вот эту штуку стоит убрать в middleware  и после обработки добавлять как параметр в аргумент w.  Так точно уйдет все дублирование кода в обработчиках запроса. Плюс в одном месте можно отдавать ошибку 401.

2022-12-22 10:16 UTC, e-faizov commented on internal/handlers/balance.go
> +	userID, err := getUserFromReq(r)
done

2022-12-23 08:25 UTC, e-faizov commented
в итоге не выдержал и добавил транзакцию в обновление заказов

2022-12-26 12:13 UTC, rktkov approved these changes

2022-12-26 12:13 UTC, rktkov commented on internal/middlewares/checkauth.go
> +	"github.com/e-faizov/gophermart/internal/models"
Не забывай про порядок импортов.

2022-12-26 12:21 UTC, merged